name: Frontend CI

on:
  push:
    branches:
      - "front-end"
      - "front-ci"

  pull_request:
    branches:
      - "front-end"
      - "front-ci"

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check and build
        run: yarn build
