name: Frontend CI

on:
  push:
    branches:
      - "front-end"
      - "front-ci"

  pull_request:
    branches:
      - "front-end"
      - "front-ci"

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-end

    steps:
      # Get repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.2"
          cache: "yarn"
          cache-dependency-path: front-end/yarn.lock

      # Install frontend dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Check Vue and TypeScript code
      - name: Type check
        run: yarn type-check
